//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectOOP_Group3.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangGiaNhaCungCap
    {
        public int ID { get; set; }
        public string MaMH { get; set; }
        public string MaNCC { get; set; }
        public decimal DonGia { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public string GhiChu { get; set; }
    
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual MatHang MatHang { get; set; }
    }
}
