//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectOOP_Group3.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPYC
    {
        public string MaPYC { get; set; }
        public string MaMH { get; set; }
        public int SoLuong { get; set; }
        public string MaNCC_Gán { get; set; }
        public Nullable<decimal> DonGiaDuKien { get; set; }
    
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual PhieuYeuCau PhieuYeuCau { get; set; }
        public virtual MatHang MatHang { get; set; }
    }
}
