//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectOOP_Group3.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonDatHang
    {
        public string MaDDH { get; set; }
        public string MaPYC { get; set; }
        public string MaNCC { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public Nullable<System.DateTime> NgayGiaoDuKien { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public string DieuKhoan { get; set; }
    
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual PhieuYeuCau PhieuYeuCau { get; set; }
    }
}
