//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectOOP_Group3.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MatHang()
        {
            this.BangGiaNhaCungCaps = new HashSet<BangGiaNhaCungCap>();
            this.ChiTietPYCs = new HashSet<ChiTietPYC>();
        }
    
        public string MaMH { get; set; }
        public string TenMH { get; set; }
        public string DonViTinh { get; set; }
        public string MaLoai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BangGiaNhaCungCap> BangGiaNhaCungCaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPYC> ChiTietPYCs { get; set; }
        public virtual LoaiMatHang LoaiMatHang { get; set; }
    }
}
