//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectOOP_Group3.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuYeuCau
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuYeuCau()
        {
            this.ChiTietPYCs = new HashSet<ChiTietPYC>();
            this.DonDatHangs = new HashSet<DonDatHang>();
        }
    
        public string MaPYC { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public string MaNV_Lap { get; set; }
        public string MaBP_YeuCau { get; set; }
        public string LyDo { get; set; }
        public string TrangThai { get; set; }
        public string MaNV_Duyet { get; set; }
        public Nullable<System.DateTime> NgayDuyet { get; set; }
        public string GhiChuDuyet { get; set; }
    
        public virtual BoPhan BoPhan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPYC> ChiTietPYCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonDatHang> DonDatHangs { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual NhanVien NhanVien1 { get; set; }
    }
}
